### PR TITLE
Russian localization fix

### PR DESCRIPTION
**Pull request by Doresun**
Fixed a few typos and errors here and there.

### CODE REVIEW

**Review by Blueberryy — APPROVED** [review]
Thanks!

**Comment by Doresun** [comment]
It seems that some strings aren't in the localization files (e.g. the new time display and date display descriptions).
Also, some of the 'circle words' in the Start menu of CL Settings humorously don't fit the circles. I guess it's because of the Russian community.properties file? Dunno.

**Comment by Blueberryy** [comment]
Yeah addon is still on beta stage so new strings will be added soon!

**Comment by Nak2** [comment]
Thanks for helping translate.
New strings might be added in the coming week.

**Pull request merged**
